config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats do
    member do # member => restaurant id in URL
      get 'image', to: "flats#image"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @flat.update(flat_params)
      redirect_to @flat
    else
      render 'edit'
    end
  end

  def destroy
    @flat.destroy
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="wrapper-body">
  <h3>Create your new flat here</h3>

  <%= simple_form_for @flat do |f| %>

    <div class="form-group">
      <%= f.label :name, "Title of your post" %><br>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :address, "Address" %><br>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :description, "Description" %><br>
      <%= f.text_field :description, class: 'form-control' %>

      <%= f.label :price_per_night, "What is the price per night?" %><br>
      <%= f.text_field :price_per_night, class: 'form-control' %>

      <%= f.label :number_of_guests, "How many guesses allowed?" %><br>
      <%= f.text_field :number_of_guests, class: 'form-control' %>

      <%= f.label :image, "Picture(s)" %><br>
      <%= f.text_field :image, class: 'form-control' %>

    </div>

    <div class="form-group">
      <%= f.submit "Submit a new flat", class: "btn btn-primary" %>
    </div>

  <% end %>

  <%= link_to "<< Back to flats listing", flats_path %>

</div>

app/views/flats/edit.html.erb
<%= render 'form' %>

app/views/flats/index.html.erb
<div class="wrapper-body">
  <div class="container">
    <div class="row">
      <% @flats.each do |flat| %>
      <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="card">
          <div class="card-img">
            <%= image_tag "#{flat.image}", class: 'img-responsive' %>
          </div>

          <div class="card-content">
            <h4><%= link_to flat.name, flat_path(flat) %></h4>
            <ul>
              <li>Address: <%= flat.address %></li>
              <li>Description: <%= flat.description %></li>
              <li>Price per night: <%= flat.price_per_night %></li>
              <li>Number of guests: <%= flat.number_of_guests %></li>
            </ul>
          </div>

        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<%= render 'form' %>

app/views/flats/show.html.erb
<div class="wrapper-body">
  <%= link_to "<< Back to flats listing", flats_path %>
  <br>
  <h3><%= @flat.name %></h3>
  <div class="card-img">
    <%= image_tag "#{@flat.image}", class: 'img-responsive' %>
  </div

  <div class="flat-details">
    <ul>
      <li>Address: <%= @flat.address %></li>
      <li>Description: <%= @flat.description %></li>
      <li>Price per night: <%= @flat.price_per_night %></li>
      <li>Number of guests: <%= @flat.number_of_guests %></li>
    </ul>
    <div class="flat-link">
      <%= link_to "Edit", edit_flat_path %> |
      <%= link_to "Delete", flat_path(@flat),
                    method: :delete,
                    data: { confirm: 'Are you sure?' } %>
    </div>

  </div>


</div>

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Simple Airbnb - Made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-custom">
  <div class="navbar-title"><h3>Simple Airbnb</h3></div>
  <div class="navbar-form">
    <div class="form-group form-inline">
      <input type="text", placeholder="Search">
      <button type="submit" class="btn btn-search">Search</button>
      <button type="submit", value="Add flat", class="btn btn-add "><%= link_to "Add flat", new_flat_path %></button>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
</head>

  <body class="site">
    <%= render "layouts/navbar" %>

    <div class="site-content">
      <%= yield %>
    </div>
  
    <%= render "layouts/footer" %>

  </body>
</html>